spring:
  application:
    name: quzrtz-cluster-node-second
  datasource:
    url: jdbc:mysql://18/lottery?serverTimezone=GMT&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: m
    password: c
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 2
      minIdle: 2
      maxActive: 30
      #StatViewServlet:
      #loginUsername: admin
      #loginPassword: admin
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler2
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            #            是否加入集群
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          dataSource:
            default:
              URL: jdbc:mysql://182.0/lottery?characterEncoding=utf-8
              user: m
              password: c
              driver: com.mysql.jdbc.Driver

    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    #jdbc:
    #initialize-schema: never
server:
  port: 8082
logging:
  level:
    com.md.luck.lottery.mapper : debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true

public:
  key: 12345678
jwt:
  secret: secret
  expiration: 7200000
  token: Authorization
weixin:
  appid: wxdaa41879edaa1cf5
  appsecret: 78e9bf4a0d432e150acdec77f0276c48
  redirecturi: http://zwpj6g.natappfree.cc/weixin/api/userInfo
  returnurl: http://4jqi4d.natappfree.cc
  loginurl: http://4jqi4d.natappfree.cc
#静态资源对外暴露的访问路径
file:
  staticAccessPath: /upload/**
  #文件上传目录（注意Linux和Windows上的目录结构不同）
  #  uploadFolder=/home/upload/
  uploadFolder: d://upload
